name: 'vudsen/intellij-plugin-verification-display'
description: 'Display your plugin verification result by replying a comment.'
branding:
  icon: map
  color: 'blue'
inputs:
  plugin-verifier-result-path:
    description: 'The verification result folder'
    required: true
  token:
    description: 'The github token'
    required: true

runs:
  using: 'node20'
  main: 'dist/bundle.js'